example/第10章/第10.2节/MyDjango/MyDjango/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('user/', include('user.urls'))
]

example/第10章/第10.2节/MyDjango/index/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page
urlpatterns = [
    # 首页的URL
    path('', cache_page(timeout=10, cache='MyDjango', key_prefix='MyDjangoURL')(views.index), name='index'),
    # 购物车
    path('ShoppingCar.html', views.ShoppingCarView, name='ShoppingCar')
]

example/第10章/第10.2节/MyDjango/user/urls.py
from django.urls import path
from . import views
urlpatterns = [
	# 用户登录
	path('login.html', views.loginView, name='login'),
	# 用户注册
	path('register.html', views.registerView, name='register'),
	# 退出登录
	path('logout.html', views.logoutView, name='logout'),
]

example/第10章/第10.2节/MyDjango/index/models.py
from django.db import models
from django.utils.html import format_html
# 创建产品分类表
# 设置字段中文名，用于admin后台显示
class Type(models.Model):
    id = models.AutoField('序号', primary_key=True)
    type_name = models.CharField('产品类型', max_length=20)
    # 设置返回值
    def __str__(self):
        return self.type_name


# 创建产品信息表
# 设置字段中文名，用于admin后台显示
class Product(models.Model):
    id = models.AutoField('序号', primary_key=True)
    name = models.CharField('名称',max_length=50)
    weight = models.CharField('重量',max_length=20)
    size = models.CharField('尺寸',max_length=20)
    type = models.ForeignKey(Type, on_delete=models.CASCADE,verbose_name='产品类型')
    # 设置返回值
    def __str__(self):
        return self.name

    class Meta:
        permissions = (
            ('visit_Product', 'Can visit Product'),
        )

example/第10章/第10.2节/MyDjango/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
class MyUser(AbstractUser):
    qq = models.CharField('QQ号码', max_length=16)
    weChat = models.CharField('微信账号', max_length=100)
    mobile = models.CharField('手机号码', max_length=11)
    # 设置返回值
    def __str__(self):
        return self.username

example/第10章/第10.2节/MyDjango/index/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.views.decorators.cache import cache_page

# 使用login_required和permission_required分别对用户登录验证和用户权限验证
@login_required(login_url='/user/login.html')
@permission_required(perm='index.visit_Product', login_url='/user/login.html')
def index(request):
	# 获取GET请求参数
	product = request.GET.get('product', '')
	price = request.GET.get('price', '')
	if product:
		# 获取存储在Session的数据，如果Session不存在product_info，则返回一个空列表
		product_list = request.session.get('product_info', [])
		# 判断当前请求参数是否已存储在Session
		if not product in product_list:
			# 将当前参数存储在列表product_list
			product_list.append({'price': price, 'product': product})
		# 更新存储在Session的数据
		request.session['product_info'] = product_list
		return redirect('/')
	return render(request, 'index.html', locals())

# 购物车
# 参数cache与全站缓存CACHE_MIDDLEWARE_ALIAS相同
# 参数key_prefix与全站缓存CACHE_MIDDLEWARE_KEY_PREFIX相同
@cache_page(timeout=10, cache='MyDjango', key_prefix='MyDjangoView')
@login_required(login_url='/user/login.html')
def ShoppingCarView(request):
	# 获取存储在Session的数据，如果Session不存在product_info，则返回一个空列表
	product_list = request.session.get('product_info', [])
	# 获取GET请求参数，如果没有请求参数，返回空值
	del_product = request.GET.get('product', '')
	# 判断是否为空，若非空，删除Session里的商品信息
	if del_product:
        # 删除Session里某个商品数据
		for i in product_list:
			if i['product'] == del_product:
				product_list.remove(i)
        # 将删除后的数据覆盖原来的Session
		request.session['product_info'] = product_list
		return redirect('/ShoppingCar.html')
	return render(request, 'ShoppingCar.html', locals())

example/第10章/第10.2节/MyDjango/user/views.py
from django.shortcuts import render, redirect
from .models import MyUser
from django.contrib.auth.models import Permission
from django.contrib.auth import login, authenticate, logout

# 用户登录
def loginView(request):
    tips = '请登录'
    title = '用户登录'
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        if MyUser.objects.filter(username=username):
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    # 登录当前用户
                    login(request, user)
                return redirect('/')
            else:
                tips = '账号密码错误，请重新输入'
        else:
            tips = '用户不存在，请注册'
    return render(request, 'user.html', locals())

# 用户注册
def registerView(request):
    title = '用户注册'
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        if MyUser.objects.filter(username=username):
            tips = '用户已存在'
        else:
            user = MyUser.objects.create_user(username=username, password=password)
            user.save()
            # 添加权限
            permission = Permission.objects.filter(codename='visit_Product')[0]
            user.user_permissions.add(permission)
            return redirect('/user/login.html')
    return render(request, 'user.html', locals())

# 退出登录
def logoutView(request):
    logout(request)
    return redirect('/')

example/第10章/第10.2节/MyDjango/index/templates/ShoppingCar.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>我的购物车</title>
{% load staticfiles %}
<link rel="stylesheet" href="{% static  'css/reset.css' %}">
<link rel="stylesheet" href="{% static  'css/carts.css' %}">
</head>
<body>
<section class="cartMain">
	<div class="cartMain_hd">
		<ul class="order_lists cartTop">
			<li class="list_chk">
				<!--所有商品全选-->
				<input type="checkbox" id="all" class="whole_check">
				<label for="all"></label>
				全选
			</li>
			<li class="list_con">商品信息</li>
			<li class="list_price">单价</li>
			<li class="list_amount">数量</li>
			<li class="list_sum">金额</li>
			<li class="list_op">操作</li>
            <li class="list_op"><a href="{% url 'index' %}">返回首页</a></li>
		</ul>
	</div>
	<div class="cartBox">
		<div class="shop_info">
			<div class="all_check">
				<!--店铺全选-->
				<input type="checkbox" id="shop_b" class="shopChoice">
				<label for="shop_b" class="shop"></label>
			</div>
			<div class="shop_name">
				店铺：<a href="javascript:;">MyDjango</a>
			</div>
		</div>
		<div class="order_content">
            {% for info in product_list %}
			<ul class="order_lists">
				<li class="list_chk">
					<input type="checkbox" id="checkbox_4" class="son_check">
					<label for="checkbox_4"></label>
				</li>
				<li class="list_con">
					<div class="list_text"><a href="javascript:;">{{ info.product }}</a></div>
				</li>
				<li class="list_price">
					<p class="price">¥{{ info.price }}</p>
				</li>
				<li class="list_amount">
					<div class="amount_box">
						<a href="javascript:;" class="reduce reSty">-</a>
						<input type="text" value="1" class="sum">
						<a href="javascript:;" class="plus">+</a>
					</div>
				</li>
				<li class="list_sum">
					<p class="sum_price">¥{{ info.price }}</p>
				</li>
				<li class="list_op">
					<p class="del">
                    <a href="{% url 'ShoppingCar' %}?product={{ info.product }}" class="delBtn">移除商品</a>
                    </p>
				</li>
			</ul>
			{% endfor %}
		</div>
	</div>
	<!--底部-->
	<div class="bar-wrapper">
		<div class="bar-right">
			<div class="piece">已选商品<strong class="piece_num">0</strong>件</div>
			<div class="totalMoney">共计: <strong class="total_text">0.00</strong></div>
			<div class="calBtn"><a href="javascript:;">结算</a></div>
		</div>
	</div>
</section>
<script src="{% static  'js/jquery.min.js' %}"></script>
<script src="{% static  'js/carts.js' %}"></script>
</body>
</html>

example/第10章/第10.2节/MyDjango/index/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}</title>
    <meta charset="utf-8">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "css/hw_index.css" %}" >
    <link rel="icon" href="{% static "img/hw.ico" %}">
    <script src="{% static "js/hw_index.js" %}"></script>
</head>
<body>
<!-- 页面顶部 -->
<!-- 顶部容器 ：width:100% -->
<header id="top">
    <!-- 内容显示区域 ：width : 1211px -->
    <div id="top_box">
        <ul class="lf">
            <li><a href="#">华为官网</a></li>
            <li><a href="#">华为荣耀</a></li>
        </ul>
        <ul class="rt">
            {# 设置缓存 #}
            {% load cache %}
            {% cache 10 MyDjangoTemp %}
            {# 在模版中使用user变量是一个User或者AnoymousUser对象，该对象由模型MyUser实例化 #}
            {% if user.is_authenticated %}
                <li>用户名: {{ user.username }}</li>
                <li><a href="{% url 'logout' %}">退出登录</a></li>
            {% endif %}
            {# 在模版中使用perms变量是Permission对象，该对象由模型Permission实例化 #}
            {% if perms.index.add_product %}
                <li>添加产品信息</li>
            {% endif %}
            {# 缓存结束 #}
            {% endcache %}
        </ul>
    </div>
</header>
<!-- logo 和 搜索框 -->
<div id="top_main">
    <div class="lf  top_main_left">
        <img src="{% static "img/newLogo.png" %}" alt="" />
    </div>
    <div class="lf search_box">
        <div class="search">
            <input type="text" class="text" id="txtSearch"/>
            <input type="button" class="button" value="搜索"/>
        </div>
        <div class="hot_words">
            <span>热门搜索：</span>
            <a href="#"> 5C</a>
            <a href="#"> HUAWEI P9</a>
            <a href="#"> 5X</a>
            <a href="#">荣耀7</a>
            <a href="#"> Mate 8</a>
        </div>
    </div>
    <div class="lf" id="my_hw">我的商城</div>
    <div class="lf" id="settle_up"><a href="{% url 'ShoppingCar' %}">我的购物车</a></div>
</div><!--top_main-->

<!-- 导航 -->
<nav id="nav">
    <div id="category">
        <a href="#">全部商品</a>
    </div>
    <ul id="nav_items" class="lf">
        <li><a href="#">首页</a></li>
        <li><a href="#">华为专区</a></li>
        <li><a href="#">荣耀专区</a></li>
    </ul>
</nav>
<!-- banner 广告 -->
<div id="banner">
    <ul id="cate_box" class="lf">
        {% for type in type_list %}
        <li>
            <h3><a href="#">{{ type.type }}</a></h3>
            <p>
                {% for name in name_list %}
                    {% if name.type == type.type %}
                        <span>{{ name.name }}</span>
                    {% endif %}
                {% endfor %}
            </p>
        </li>
        {% endfor %}
    </ul>
    <!--图片轮播 -->
    <form>
        <div class="slider">
            <img id="slider_img" class="img_slider" src="{% static "img/slide01.png" %}" alt=""/>
        </div>
    </form>
</div>
<div class="hr-2"></div>
<!-- 网页主体 -->
<section id="main">
    <div class="layout">
        <div class="fl u-4-3 lf">
            <ul>
                <li class="channel-pro-item">
                    <!--<i class="p-tag"><img src="img/new_ping.png" style="padding-left: 0" alt=""/></i>-->
                    <div class="p-img">
                        <img src="{% static "img/phone01.png" %}" alt=""/>
                    </div>
                    <div class="p-name lf"><a href="#">HUAWEI P9 Plus</a></div>
                    <div class="p-shining">
                        <div class="p-slogan">一上手，就爱不释手</div>
                        <div class="p-promotions">5月6日10:08 火爆开售</div>
                    </div>
                    <div class="p-price">
                        <em>¥</em>
                        <span>3988</span>
                    </div>
                    <div class="p-button lf">
                        <a href="{% url 'index' %}?product=HUAWEI P9 Plus&price=3988">立即抢购</a>
                    </div>
                </li>
                <li class="channel-pro-item" style="background-color:#E2F9FB"><!--荣耀畅玩5C-->
                    <!--<i class="p-tag"><img src="img/new_ping02.png" alt=""/></i>-->
                    <div class="p-img">
                        <img src="{% static "img/phone02.png" %}" alt=""/>
                    </div>
                    <div class="p-name lf"><a href="#">荣耀畅玩5C</a></div>
                    <div class="p-shining">
                        <div class="p-slogan">16纳米8核芯千元普及风暴</div>
                        <div class="p-promotions">5月10日10:08震撼开售</div>
                    </div>
                    <div class="p-price">
                        <em>¥</em>
                        <span>899</span>
                    </div>
                    <div class="p-button lf">
                        <a href="{% url 'index' %}?product=荣耀畅玩5C&price=899">立即抢购</a>
                   </div>
                </li>
                <div class="hr-2"></div>
                <li class="channel-pro-item" style="background-color:#FFFCE7"><!--荣耀畅玩5C-->
                    <!--<i class="p-tag"><img src="img/hot_but.png" alt=""/></i>-->
                    <div class="p-img">
                        <img src="{% static "img/phone05.png" %}" alt=""/>
                    </div>
                    <div class="p-name lf"><a href="#">荣耀7</a></div>
                    <div class="p-shining">
                        <div class="p-slogan">智灵键，创新语音控制</div>
                        <div class="p-promotions">移动增强版原价1999直降200</div>
                    </div>
                    <div class="p-price">
                        <em>¥</em>
                        <span>1799</span>
                    </div>
                    <div class="p-button lf">
                        <a href="{% url 'index' %}?product=荣耀7&price=1799">立即抢购</a>
                    </div>
                </li>
                <li class="channel-pro-item" style="background-color:#FFECEF"><!--荣耀畅玩5C-->
                    <!--<i class="p-tag"><img src="img/hot_but.png" alt=""/></i>-->
                    <div class="p-img">
                        <img src="{% static "img/phone06.png" %}" alt=""/>
                    </div>
                    <div class="p-name lf"><a href="#">荣耀畅玩5X</a></div>
                    <div class="p-shining">
                        <div class="p-slogan">腾讯视频VIP特权免费领</div>
                        <div class="p-promotions">5月4日至8日 每天10:08/20:00准点开售</div>
                    </div>
                    <div class="p-price">
                        <em>¥</em>
                        <span>899</span>
                    </div>
                    <div class="p-button lf">
                        <a href="{% url 'index' %}?product=荣耀畅玩5X&price=899">立即抢购</a>
                    </div>
                </li>
            </ul>
        </div><!-- u-4-3结束-->
        <div class="lf fr u-4-1">
            <div class="channel-sale">
                <img src="{% static "img/phone03.jpg" %}" alt=""/>
            </div>
            <div class="hr-2"></div>
            <ul class="h-tab">
                <li class="current" id="tab-notice">
                    <a href="#">公告</a>
                </li>
                <li id="tab-news" class="">
                    <a href="#">评测 </a>
                </li>
                <div class="b">
                    <ul id="tab-notice-content" style="display:block;">
                        <li>
                            <a href="#">HUAWEI G9 青春版震撼首发，全款预订赢好礼</a>
                        </li>
                        <li>
                            <a href="#">荣耀畅玩5C，真芯不怕！ 5月5日10:08震撼首发！</a>
                        </li>
                        <li>
                            <a href="#">参与互动赢荣耀畅玩5C，与“胖红”一起怒FUN！</a>
                        </li>
                        <li>
                            <a href="#">【中奖名单】HUAWEI WATCH星月系列购机抽奖</a>
                        </li>
                    </ul>
                </div>
            </ul>
        </div>
        <div class="hr-2"></div>
        <div class="banner">
            <img class="rt" src="{% static "img/vip.jpg" %}" alt=""/>
            <div class="hr-2"></div>
        </div>
    </div><!--layout HUAWEI P9 Plus结束-->
</section>


<div class="hr-2"></div>
   <div id="banner_img">
    <div class="banner-slideshow">
        <img src="{% static "img/p9.jpg" %}" width="100%" alt=""/>
    </div>
    </div>
</div>
<div class="hr-2"></div>
<div class="hr-40"></div>
<div class="slogan">
   <ul>
       <li class="s1"><i>500强企业 品质保证</i></li>
       <li class="s1"><i>7天退货 15天换货 </i></li>
       <li class="s1"><i>99元起免运费</i></li>
       <li class="s1"><i>448家维修网点 全国联保</i></li>
   </ul>
</div>

</body>
</html>